name 'elixir_development'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
license 'all_rights'
description 'Prepares an Elixir devleopment environment'
long_description 'Prepares an Elixir devleopment environment'
version '0.1.0'
depends 'apt'
