include_recipe 'elixir_development::dotfiles'
include_recipe 'elixir_development::elixir'
include_recipe 'elixir_development::postgres'
include_recipe 'elixir_development::mysql'
include_recipe 'elixir_development::nodejs'
include_recipe 'elixir_development::phoenix'
